# Generated by Django 3.1.3 on 2020-11-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                (
                'document_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=64, verbose_name='Apellido')),
                ('medical_history', models.TextField(max_length=256, verbose_name='Historia Medica')),
            ],
        ),
    ]
