# Generated by Django 3.1.3 on 2020-11-14 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
