# Generated by Django 3.1.3 on 2020-11-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True, verbose_name='Fecha')),
                ('attended', models.BooleanField(default=False, verbose_name='¿Atendido?')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente',
                                              to='patient.patient', verbose_name='Paciente')),
            ],
        ),
    ]
