# Generated by Django 3.1.3 on 2020-11-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0002_auto_20201114_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=0.0004950495049504951, unique=True, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
