# Generated by Django 3.1.3 on 2020-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0003_auto_20201114_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, unique=True, verbose_name='Fecha'),
        ),
    ]
