# Generated by Django 3.1.3 on 2020-11-14 19:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0004_auto_20201114_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, unique=True, verbose_name='Fecha'),
        ),
    ]
