# Generated by Django 3.1.3 on 2020-11-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0005_auto_20201114_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(unique=True, verbose_name='Fecha'),
        ),
    ]
