# Generated by Django 3.1.3 on 2020-11-14 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0006_auto_20201114_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='attended',
            new_name='was_present',
        ),
    ]
