# Generated by Django 3.1.3 on 2020-11-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0008_auto_20201114_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='was_present',
            field=models.BooleanField(default=False, verbose_name='¿Atendido?'),
        ),
    ]
