# Generated by Django 3.1.3 on 2020-11-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status',
                 models.CharField(choices=[('PED', 'Pedido'), ('TAL', 'Taller'), ('PEN', 'Pendiente')], default='PEN',
                                  max_length=3)),
                ('payment_method', models.CharField(
                    choices=[('CRED', 'Tarjeta de Credito'), ('DBTO', 'Tarjeta de Debito'),
                             ('VIRT', 'Billetera Virtual'), ('EFEC', 'Efectivo')], default='EFEC', max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('products', models.ManyToManyField(related_name='Productos', to='orders.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
