# Generated by Django 3.1.3 on 2020-11-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patient', '0002_auto_20201114_2007'),
        ('orders', '0003_auto_20201114_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient',
                                    verbose_name='Paciente'),
        ),
    ]
