# Generated by Django 3.1.3 on 2020-11-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_auto_20201114_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
