# Generated by Django 3.1.3 on 2020-11-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0005_auto_20201114_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
