# Generated by Django 3.1.3 on 2020-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201120_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_glass',
            field=models.BooleanField(default=False, verbose_name='Lente'),
        ),
    ]
