# Generated by Django 3.1.3 on 2020-11-20 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_auto_20201120_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='Vendedor'), on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
