# Generated by Django 3.1.3 on 2020-11-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20201120_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PED', 'Pedido'), ('TAL', 'Taller'), ('PEN', 'Pendiente'), ('FIN', 'Finalizado')], default='PEN', max_length=3),
        ),
    ]
