# Generated by Django 3.1.3 on 2020-11-23 21:34

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20201123_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Fecha'),
        ),
    ]
