# Generated by Django 3.1.3 on 2020-11-29 04:05

import datetime

import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20201123_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 4, 5, 50, 550827, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2020, 11, 29, 4, 5, 50, 550841, tzinfo=utc), message='Ingrese una fecha y/u horario posterior.')], verbose_name='Fecha'),
        ),
    ]
